### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by briis** [caseda/com.aeotec#4]
Hi,
Just downloaded this, but I am getting the following error when trying to install:

? Select active Homey: Homey Stue @ 192.168.1.239:80
1/3 - Archiving...
2/3 - Uploading to Homey Stue @ 192.168.1.239:80...
Invalid JSON in app.json [SyntaxError: Unexpected string]

**Comment by briis** [comment]
I found thew error. In Line 871 there was a comma (,) missing after the value. After inserting that, the installation went fine.

**Comment by briis** [comment]
After installation, Homey reports the following error:
Stack trace:

Error: Cannot find module 'homey-zwavedriver'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/drivers/DSB05/driver.js:3:21)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)

Exit code: 1
Exit signal: null

**Comment by caseda** [comment]
you still need to install the z-wave drivers:
https://github.com/athombv/node-homey-zwavedriver/commits/master

**Comment by briis** [comment]
I did, and it works. Just installed the Multi Sensor 4, Gen 5 and it works like a charm :) Will do some more testing over the next day.

**Comment by caseda** [comment]
have you had the chance to test the driver more yet?

just curious, so we can finally implement it into the app.

**Comment by briis** [comment]
Hi,
Sorry. Forgot to come back. Yes I have testet it, and found no problems.

De bedste hilsner,

Bjarne Riis
Søholmvej 38
3480 Fredensborg
Tlf: 4916 2414
Mobil: 2619 1701
E-Mail: bjarne@briis.com<mailto:bjarne@briis.com>
